plugin: cisco.dnac.dnac_inventory
dnac_host: sandboxdnac.cisco.com
dnac_username: devnetuser
dnac_password: Cisco123!
dnac_verify: false

group_by:
- platform
- siteName

hostvar_expressions:
  ansible_host: managementIpAddress
  ansible_network_os: softwareType | lower
